/* Generated By:JavaCC: Do not edit this line. WMParser_implConstants.java */
package org.webmacro.parser;

public interface WMParser_implConstants {

  int EOF = 0;
  int _ALPHA_CHAR = 1;
  int _NUM_CHAR = 2;
  int _ALPHANUM_CHAR = 3;
  int _IDENTIFIER_CHAR = 4;
  int _IDENTIFIER = 5;
  int _NEWLINE = 6;
  int _WHITESPACE = 7;
  int _QCHAR = 8;
  int _COMMENT = 9;
  int STUFF = 10;
  int BEGIN = 11;
  int END = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int COMMENT = 16;
  int DOLLAR = 17;
  int QCHAR = 18;
  int SLASH = 19;
  int POUND = 20;
  int QUOTE = 21;
  int NULL = 22;
  int TRUE = 23;
  int FALSE = 24;
  int WORD = 25;
  int WS = 26;
  int NEWLINE = 27;
  int LPAREN = 28;
  int RPAREN = 29;
  int LBRACKET = 30;
  int RBRACKET = 31;
  int DOT = 32;
  int OP_LT = 33;
  int OP_LE = 34;
  int OP_GT = 35;
  int OP_GE = 36;
  int OP_EQ = 37;
  int OP_SET = 38;
  int OP_NE = 39;
  int OP_PLUS = 40;
  int OP_MINUS = 41;
  int OP_MULT = 42;
  int OP_DIV = 43;
  int OP_AND = 44;
  int OP_OR = 45;
  int OP_NOT = 46;
  int COMMA = 47;
  int NUMBER = 48;
  int OTHER = 49;
  int QS_TEXT = 50;

  int QS = 0;
  int WM = 1;
  int DEFAULT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<_ALPHA_CHAR>",
    "<_NUM_CHAR>",
    "<_ALPHANUM_CHAR>",
    "<_IDENTIFIER_CHAR>",
    "<_IDENTIFIER>",
    "<_NEWLINE>",
    "<_WHITESPACE>",
    "<_QCHAR>",
    "<_COMMENT>",
    "<STUFF>",
    "\"#begin\"",
    "\"#end\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 15>",
    "<COMMENT>",
    "\"$\"",
    "<QCHAR>",
    "\"\\\\\"",
    "\"#\"",
    "\"\\\"\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "<WORD>",
    "<WS>",
    "<NEWLINE>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\",\"",
    "<NUMBER>",
    "<OTHER>",
    "<QS_TEXT>",
  };

}
