   <TABLE BORDER="1" BGCOLOR="silver" BORDER="0" CELLPADDING="4" CELLSPACING="0">
   <TR><TH COLSPAN="5">
      #if(!$display2){ 
         #set $display2="0"
      } 
      <INPUT TYPE="Text" VALUE="$display2" NAME="number" READONLY>
   </TH></TR>
   <TR><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 7 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 8 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 9 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" / "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="sin(x)">
   </TD></TR>
   <TR><TD>   
      <INPUT TYPE="Submit" NAME="action" VALUE=" 4 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 5 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 6 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" * "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="cos(x)">
   </TD></TR>
   <TR><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 1 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 2 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 3 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" - "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="sqrt(x)">
   </TD></TR>
   <TR><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" 0 "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="+/-"></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="  .  "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" + "></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="x^y">
   </TD></TR>
   <TR><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE="CE"></TD><TD>
      <INPUT TYPE="Submit" NAME="action" VALUE=" C "></TD><TD COLSPAN=3>
      <INPUT TYPE="Submit" NAME="action" VALUE="         =         "></TD>
   </TR></TABLE>
